### PR TITLE
Change t-mobile UK to EE and update to current EE credentials

### PR DESCRIPTION
**Pull request by atlochowski**
Change t-mobile UK to EE and update to current EE credentials

### CODE REVIEW

**Review by monich — APPROVED** [review]
I'll trust you)

**Comment by atlochowski** [comment]
> I'll trust you)

Thanks for trusting me, but just in case you can check it here https://en.m.wikipedia.org/wiki/T-Mobile_UK

**Comment by monich** [comment]
> Thanks for trusting me, but just in case you can check it here https://en.m.wikipedia.org/wiki/T-Mobile_UK

I think it would be a good idea to include such links in the description of the PR

**Comment by atlochowski** [comment]
> > Thanks for trusting me, but just in case you can check it here https://en.m.wikipedia.org/wiki/T-Mobile_UK
> 
> I think it would be a good idea to include such links in the description of the PR

I've edited this file a lot in the past making changes and you always trusted me.
I always try to double check before making any changes.
In the future, I will try to include a link to information about the change

**Pull request merged**
